#!/usr/bin/with-contenv bashio
# Reads HA addon options, generates config.toml, starts zeroclaw daemon.

set -euo pipefail

CONFIG_DIR="/config/zeroclaw"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
TOKEN_FILE="${CONFIG_DIR}/.bearer_token"
OPTIONS_FILE="/data/options.json"

# --- Read addon options ---
LLM_PROVIDER=$(jq -r '.llm_provider' "${OPTIONS_FILE}")
API_KEY=$(jq -r '.api_key' "${OPTIONS_FILE}")
DEFAULT_MODEL=$(jq -r '.default_model // ""' "${OPTIONS_FILE}")
GATEWAY_PORT=$(jq -r '.gateway_port // 42617' "${OPTIONS_FILE}")

# --- Apply extra env vars ---
ENV_COUNT=$(jq '.env_vars | length' "${OPTIONS_FILE}")
for i in $(seq 0 $((ENV_COUNT - 1))); do
  NAME=$(jq -r ".env_vars[$i].name" "${OPTIONS_FILE}")
  VALUE=$(jq -r ".env_vars[$i].value" "${OPTIONS_FILE}")
  export "${NAME}=${VALUE}"
done

# --- Pre-seed bearer token (reuse across restarts) ---
mkdir -p "${CONFIG_DIR}"
if [ -f "${TOKEN_FILE}" ]; then
  BEARER_TOKEN=$(cat "${TOKEN_FILE}")
else
  BEARER_TOKEN="zc_$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  printf '%s' "${BEARER_TOKEN}" > "${TOKEN_FILE}"
  chmod 600 "${TOKEN_FILE}"
fi

# --- Generate config.toml ---
cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by ZeroClaw HA addon — edits will be overwritten on restart.

default_provider = "${LLM_PROVIDER}"
api_key = "${API_KEY}"
EOF

if [ -n "${DEFAULT_MODEL}" ]; then
  echo "default_model = \"${DEFAULT_MODEL}\"" >> "${CONFIG_FILE}"
fi

cat >> "${CONFIG_FILE}" <<EOF

[gateway]
host = "0.0.0.0"
port = ${GATEWAY_PORT}
allow_public_bind = true
paired_tokens = ["${BEARER_TOKEN}"]
EOF

chmod 600 "${CONFIG_FILE}"

bashio::log.info "Starting ZeroClaw daemon (provider=${LLM_PROVIDER}, port=${GATEWAY_PORT})"

# --- Start ZeroClaw ---
exec zeroclaw daemon --config-dir "${CONFIG_DIR}"
